# -*- coding: utf-8 -*-
"""Brazilian ecomm.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qlmK7VFr_lJiGIN0GDUXMfYraYKUav_5

## Brazilian Ecommerce Data Analysis

Importing all the files
"""

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import os
from pandas_profiling import ProfileReport

from google.colab import drive
drive.mount('/content/drive')



print('### Marketing Funnel by Olist ###')

for idx, file in enumerate(os.listdir('/content/drive/My Drive/Brazilian-ecommerce/marketing-funnel')):
    print(idx, '-', file)
print('\n---------------------------------------------\n')

print('### Brazilian E-Commerce Public Dataset by Olist ###')
for idx, file in enumerate(os.listdir('/content/drive/My Drive/Brazilian-ecommerce/brazilian-ecomm')):
    print(idx, '-', file)

"""## Processing the Marketing Funnel Datasets

"""

# closed deals dataset
closed_deals= pd.read_csv('/content/drive/My Drive/Brazilian-ecommerce/marketing-funnel/olist_closed_deals_dataset.csv')

# leads dataset
mql = pd.read_csv('/content/drive/My Drive/Brazilian-ecommerce/marketing-funnel/olist_marketing_qualified_leads_dataset.csv')

"""## Processing the Brazilian Ecommerce Datasets"""

# customer dataset
customer = pd.read_csv('/content/drive/My Drive/Brazilian-ecommerce/brazilian-ecomm/olist_customers_dataset.csv')
# geolocation dataset
geolocation = pd.read_csv('/content/drive/My Drive/Brazilian-ecommerce/brazilian-ecomm/olist_geolocation_dataset.csv')
# order payment dataset
ord_pay = pd.read_csv('/content/drive/My Drive/Brazilian-ecommerce/brazilian-ecomm/olist_order_payments_dataset.csv')
# order reviews dataset
ord_review = pd.read_csv('/content/drive/My Drive/Brazilian-ecommerce/brazilian-ecomm/olist_order_reviews_dataset.csv')
# order items dataset
ord_items = pd.read_csv('/content/drive/My Drive/Brazilian-ecommerce/brazilian-ecomm/olist_order_items_dataset.csv')
# products dataset
products = pd.read_csv('/content/drive/My Drive/Brazilian-ecommerce/brazilian-ecomm/olist_products_dataset.csv')
# orders dataset
orders = pd.read_csv('/content/drive/My Drive/Brazilian-ecommerce/brazilian-ecomm/olist_orders_dataset.csv')
# sellers dataset
sellers = pd.read_csv('/content/drive/My Drive/Brazilian-ecommerce/brazilian-ecomm/olist_sellers_dataset.csv')
# product category translation dataset
prod_cat_trans = pd.read_csv('/content/drive/My Drive/Brazilian-ecommerce/brazilian-ecomm/product_category_name_translation.csv')

"""## File Inspection. 
We will check each dataset here to get an idea about their content. BAsed on the requirement of the project, we will delve deeper into the file we need 
"""

customer.head()

geolocation.head()

ord_pay.head()

ord_review.head()

ord_items.sort_values(by= 'order_item_id')

products.head()

# Translating product categories from Portugese to English
category_translated = dict(zip(prod_cat_trans['product_category_name'],prod_cat_trans['product_category_name_english']))
products = products.replace({'product_category_name':category_translated})
products.head()

prod_cat_trans.head(10)

orders.head()

orders.groupby('order_status').order_id.count()

sellers.head()

"""## RFM Analysis
For RFM analysis, we need to know the recency , frequency and monetary values for each customer. We will need to collect information from the following datasets:
1. Customer
2. Order
3. Order Item
4. Products


"""





products.head(10)

